### ISSUE TITLE
`examples/MQ/serialization/1-simple` fails often in containerized CI build

### ISSUE THREAD

**Issue by dennisklein** [FairRootGroup/FairRoot#1048]
`examples/MQ/serialization/1-simple` fails quite often in the CI singularity container builds most likely due to timing:

Example log: https://cdash.gsi.de/testDetails.php?test=7967809&build=266492

Looks to me as if the processor shuts down too fast?

**Comment by rbx** [comment]
Sink is waiting to receive here, I would say latest at `18:43:59.588961`:
```
[ex-serialization1-sink][18:43:58.578306][INFO][FairMQDevice.cxx:449:RunWrapper] DEVICE: Running...
[ex-serialization1-sink][18:43:59.588961][INFO][FairMQDevice.cxx:760:LogSocketRates] data2[0]: in: 0 (0 MB) out: 0 (0 MB)
[ex-serialization1-sink][18:44:00.589102][INFO][FairMQDevice.cxx:760:LogSocketRates] data2[0]: in: 0 (0 MB) out: 0 (0 MB)
[ex-serialization1-sink][18:44:01.589229][INFO][FairMQDevice.cxx:760:LogSocketRates] data2[0]: in: 0 (0 MB) out: 0 (0 MB)
```
Processor queues his messages latest at `18:44:00.798466`:

```
[ex-serialization1-processor][18:44:00.368985][INFO][FairMQDevice.cxx:449:RunWrapper] DEVICE: Running...
[ex-serialization1-processor][18:44:00.798466][INFO][Ex1Processor.h:61:Run] Received 100 and sent 100 messages!
[ex-serialization1-processor][18:44:00.798559][INFO][FairMQDevice.cxx:760:LogSocketRates] data1[0]: in: 233.645 (30.8636 MB) out: 0 (0 MB)
```

ZeroMQ transport has linger value of 1000ms. Looks like processor did make use of it, at least partially (it happens during ResettingDevice state):
```
[ex-serialization1-processor][18:44:00.798847][STATE][StateMachine.cxx:195:ProcessWork] DEVICE READY ---> RESETTING DEVICE
[ex-serialization1-processor][18:44:01.300453][STATE][StateMachine.cxx:195:ProcessWork] RESETTING DEVICE ---> IDLE
```
Half a second wait (usually it is much faster)... half a second is strange, since it wasn't a whole second, suggests it could've succeeded to send it out. But nothing arrived... strange.

I will modify the example so that sampler and processor do not exit by themselves at all. Sink will exit once he gets all the messages and then the other two are killed.

**Comment by rbx** [comment]
Hmm, not exiting from Processor is simple, he can just hang in `Receive` for the next message. But sampler should go to `Ready` state once it is done. The test is ran with a static controller, so going to `Ready` will eventually lead to device shutdown. At least from this log it doesn't look like it would be an issue, but in principle this kind of fail could then happen again (if the sampler is too slow to actually properly send out the data).

A solution would be to switch to a proper controller here. This would mean introducing DDS dependency for this example. Objections, other ideas?

**Comment by dennisklein** [comment]
Last 500 runs there was only 1 failure, seems stable enough to close this.
