### ISSUE TITLE
Missing lib path in config.sh

### ISSUE THREAD

**Issue by ghost** [FairRootGroup/FairRoot#107]
I use FairRoot v-14.11 with external packages jul14p3. 
In the build directory of jul14p3 are (in my case) two lib directories "lib" and "lib64". 
The config.sh of fairroot v-14.11 adds just "lib" to the $LD_LIBRARY_PATH and not the "lib64".
Due to this my software crashes because i need the libprotobuf from the "lib64" directory.

Is this suppose to be like that or is the directory missing?

**Comment by fuhlig1** [comment]
Hi Ghost,

this problem occurs only on some systems. For example SLC installs some stuff in lib64. In the development branch of FairSoft this issue is already fixed by creating a lib directory and a symbolic link from lib64 to lib before starting with the installation of the package of FairSoft. With this fix in the end there is only one directory which contain all libraries.

Ciao

Florian
