### ISSUE TITLE
FairRootConfig.sh minor issues

### ISSUE THREAD

**Issue by klenze** [FairRootGroup/FairRoot#1085]
I just did a fresh make install on the dev version of FairRoot, and the configuration generated by FairRootConfig.sh leaves some room for improvement, in my opinion. 

**To Reproduce**
```bash
git clone ...
mkdir fairroot_build && cd fairroot_build
cmake -DCMAKE_TOOLCHAIN_FILE=$PWD/../toolchain.cmake -DCMAKE_INSTALL_PREFIX=$PWD/../fairroot_inst/ \
  ../FairRoot -DCMAKE_FIND_USE_PACKAGE_REGISTRY=0
make -j install
cat ../fairroot_inst/bin/FairRootConfig.sh
```

Results (reordered, dubious only, #comments are mine)
```bash
#empty env variables:
export ROOTSYS="" #empty
export FAIRROOTPATH="" #also empty
export G3SYS="" # but Geant3_... stuff is set?
# set twice:
export Geant3_INCLUDE_DIRS="/path/to/fairsoft_inst/include/TGeant3"
#other (won't argue about it):
export VMCWORKDIR="/path/to/fairroot_inst/share/fairbase/examples" 
#overwritten general env:
export CLASSPATH="" #never liked java anyhow
export PYTHONPATH="/path/to/git/repo/of/FairRoot/python:[...]" # does not actually exist
case $1 in
#[...]
* ) #$1 is neither -a nor -p
   export DYLD_LIBRARY_PATH="" #some apple thing?
   LD_LIBRARY_PATH="/path/to/fairroot_inst/lib:/path/to/fairsoft_inst/lib" # hope there was nothing important in before
   export PATH="/bin" # at least it is not empty
;;
```

Some remarks. 
None of this is very serious, figuring out that ROOTSYS should be /path/to/fairsoft_inst/ and FAIRROOTPATH should be /path/to/fairroot_inst/ is rather obvious.
In R3BRoot, I have always used VMCWORKDIR as "that variable helpfully pointing to my git repository", but that is probably not what it is for?
Overwriting CLASSPATH and PYTHONPATH unconditionally could actually annoy users of java or python who rely on it. Any variables not invented by FairRoot or FairSoft packages (e.g. ROOT) should go into the case block, in my opinion.

Speaking of that case block, I think it nice to give the users a prepend and append option. However, I think "replace" is a terrible default.
LD_LIBRARY_PATH will just hit a minority of users. But the PATH assignment will annoy virtually everyone. 

I see room for two options in the case statement. 
The default should be to prepend. The user is sourcing us, they probably want to use our libraries.
(I am doubtful if append (which means "use this version of root only if you do not have the system package installed") has a practical use case.)
For users who want to either a) repeatedly source FairRootConfig.sh (without getting the same item into their variables more than once) or b) toggle between different versions of fairsoft/fairroot without stating a new shell, a good compromise would be to set these variables to Fair* directories + whatever was in them when cmake ../FairRoot/ was run. Sourcing this should be idempotent and clean up leftover stuff, while still being hopefully useful (no PATH=/just/fairroot/stuff). But again, a new shell is just one bash -l away, so why bother?

On an unrelated note, I found that some cmake packages (so far for /u/land: Garfield, yaml-cpp) tend to hide their configuations in ~/.cmake/packages/, where they will "helpfully" be found by subsequent cmake invocations irregardless of env variables. The 
```-DCMAKE_FIND_USE_PACKAGE_REGISTRY=0``` puts a stop to this.

**Comment by dennisklein** [comment]
> None of this is very serious, figuring out that ROOTSYS should be /path/to/fairsoft_inst/ and FAIRROOTPATH should be /path/to/fairroot_inst/ is rather obvious.

Most of those variables just need to go away (they are already made obsolete by default). Since 2017 I have basically an open CMake modernization effort and the `FairRootConfig.sh` facility is the hardest to modernize. Its existance is an anti-pattern that is very common in our community. Many HEP software packages **require** the user to set up the environment usually by sourcing some `<app>_env.sh` which contains only information known at compile-time. So, why **requiring** it at all and not default to this knowledge and only allow the user to configure optionally via a environment variable.

> In R3BRoot, I have always used VMCWORKDIR as "that variable helpfully pointing to my git repository", but that is probably not what it is for?

I am honestly still puzzled what this variable is needed for (but I also never really investigated myself).

> Overwriting CLASSPATH and PYTHONPATH unconditionally could actually annoy users of java or python who rely on it. Any variables not invented by FairRoot or FairSoft packages (e.g. ROOT) should go into the case block, in my opinion.
>
> Speaking of that case block, I think it nice to give the users a prepend and append option. However, I think "replace" is a terrible default.
> LD_LIBRARY_PATH will just hit a minority of users. But the PATH assignment will annoy virtually everyone.
> I see room for two options in the case statement.
> The default should be to prepend. The user is sourcing us, they probably want to use our libraries.
> (I am doubtful if append (which means "use this version of root only if you do not have the system package installed") has a practical use case.)
> For users who want to either a) repeatedly source FairRootConfig.sh (without getting the same item into their variables more than once) or b) toggle between different versions of fairsoft/fairroot without stating a new shell, a good compromise would be to set these variables to Fair* directories + whatever was in them when cmake ../FairRoot/ was run. Sourcing this should be idempotent and clean up leftover stuff, while still being hopefully useful (no PATH=/just/fairroot/stuff). But again, a new shell is just one bash -l away, so why bother?

Absolutely with you, I raised these points in the past, but was overruled by other FairRoot developers. To me, there is exactly one way to touch these kind of "search path" type of variables and that is **prepend**. There is even a build option [`USE_PATH_INFO`](https://github.com/FairRootGroup/FairRoot/blob/906f6e8493284f083b3d30a50b9001cce5109007/CMakeLists.txt#L96-L105) which records the `$PATH` and `$LD_LIBRARY_PATH` at build time and bakes it into the FairRoot install tree which is completely which is a completely insane and broken thing to do in my opinion ...

> On an unrelated note, I found that some cmake packages (so far for /u/land: Garfield, yaml-cpp) tend to hide their configuations in ~/.cmake/packages/, where they will "helpfully" be found by subsequent cmake invocations irregardless of env variables. The
> `-DCMAKE_FIND_USE_PACKAGE_REGISTRY=0` puts a stop to this.

Yes, but what is your suggestion? Should FairRoot switch this off by default?

---

On a more general note, many things `FairRootConfig.sh` is used for, is actually the responsibility of a package manager, but historically things never got packaged properly and then those deficits got solved in all kinds of "wrong" places and it turns out to be a hugely complex task to clean this up (as I said, I saw all this in 2017 and now it is 2021 and I still do not have sane solution paths for all subtle aspects of the current state). The guiding idea is to disentangle this tight relationship between FairRoot and the <Experiment>Root to become a plain standard CMake library dependency relationship. Unfortunately this is not yet achieved.

All this heavy usage of `LD_LIBRARY_PATH` is actually also an anti-pattern (not only the fact that the default is *replace*). @ChristianTackeGSI and I have seen many cases where setting it - with the main goal of telling the root interpreter where to search things - would also break other applications used in such a shell session, including the terminal emulator itself... Cleaning those anti-patterns takes time, e.g. to not have to use `LD_LIBRARY_PATH` any more, @ChristianTackeGSI added `ROOT_LIBRARY_PATH` to Root, which landed only recently in [6.24/00](https://root.cern/doc/v624/release-notes.html#dynamic-path-root_library_path).

If you are further interested in this kind of work, we can take this offline and discuss together with @ChristianTackeGSI why we are going to introduce breaking changes (on the CMake level) in FairRoot v19.0 and how the <Experiment>Root (in your case R3BRoot) can/should adapt to them.

In any case, thank you for the issue and making these very valid observations. Even though they are basically *known issues* (to me and @ChristianTackeGSI), let's keep this issue as an additional todo item.

**Comment by ChristianTackeGSI** [comment]
> > In R3BRoot, I have always used VMCWORKDIR as "that variable helpfully pointing to my git repository", but that is probably not what it is for?
> 
> I am honestly still puzzled what this variable is needed for (but I also never really investigated myself).

I started to look around a bit on this one.
 First observation: Different parts of the code expect this variable to point to different directories:
* Some expect it to point to the main git directory of FairRoot (or some examples related directory in the install tree).
* Some expect it to point to a directory holding a `/gconfig/`, or `/geometry/` directory.
* Some have a default of `cbmout`, `cbmroot`, `cbmsim` if $VMCWORKDIR is not set. And if it is set and satisfies some criteria, then even memory is leaked.

What also complicates things: Using the directories at development time (source / build tree) and after installation (install tree). This is currently handled by two `FairRootConfig.sh` scripts being generated.

From my current perspective, this variable should go away entirely. Its name isn't even related to FairRoot!
One should probably go around and reverse engineer different use cases and conclude for them how to handle them.

**Comment by fuhlig1** [comment]
The variable VMCWORKDIR points to the directory where you find the geometries and other inputs. This variable is absolutely needed for the runtime. Otherwise none of the macros will work.

**Comment by dennisklein** [comment]
> The variable VMCWORKDIR points to the directory where you find the geometries and other inputs.

* Is it only inputs - or in other words, must `VMCWORKDIR` be writable by the user (asking because of the `WORK` in `VMCWORKDIR`)?
* Is this a FairRoot-only variable, or is it also used by other packages?

> One should probably go around and reverse engineer different use cases and conclude for them how to handle them.

I guess, the first step I would like to see is to find usages of `VMCWORKDIR` in the macros etc and replace direct access to environment variable with an API that can provide the default value, so we eventually no longer require this variable to be defined (of course, if it is set, it should behave as an override to the default value).

**Comment by ChristianTackeGSI** [comment]
> I guess, the first step I would like to see is to find usages of `VMCWORKDIR` in the macros etc and replace direct access to the environment variable with an API that can provide the default value, so we eventually no longer require this variable to be defined (of course, if it is set, it should behave as an override to the default value).

:+1: 

My impression was, that there are multiple, distinct use cases. So that might ask for multiple such APIs?

We could of course start with a generic one?

**Comment by dennisklein** [comment]
To me, it appears as if `FairGenericVMCConfig::GetWorkdir()` could be a suitable place?!

This would then be used instead of e.g. https://github.com/FairRootGroup/FairRoot/blob/18b71c213423ba2f4a6082e3c69c570cedcb4f51/examples/simulation/Tutorial2/macros/create_digis.C#L16

**Comment by dennisklein** [comment]
21c7535b6, b000eb39d, d27dfaf24 scheduled for release in v18.8
