### ISSUE TITLE
JSON parsing in FairRoot and inheriting packages

### ISSUE THREAD

**Issue by rklasen** [FairRootGroup/FairRoot#1116]
**Is your feature request related to a problem? Please describe.**

Hi, at PandaRoot we use json files for parameter exchange. Currently I'm including [nlohmanns header-only json parser](https://github.com/nlohmann/json), but it has to be kept updated manually. Also, it's only available for our (LMD) groups, which is sub-optimal if other users use json too.

**Describe the solution you'd like**

Would you be interested in including nlohmanns json parser [via CMAKEs fetch content](https://github.com/nlohmann/json#cmake)? If I'm understanding this correctly, the addition should be a simple addition to the main CMakeLists file, this way the json library would be pulled and built with FairRoot.

**Describe alternatives you've considered**

If not, we could also add the include in either PandaRoot, or only our groups CMakeLists.

**Additional context**

Or is there already an established way to parse json which I'm not familiar with?

**Comment by AndreyLebedev** [comment]
@rklasen Consider using [`boost::property_tree`](https://www.boost.org/doc/libs/1_77_0/doc/html/property_tree.html). It has JSON and XML parsers out of the box.

**Comment by dennisklein** [comment]
> Would you be interested in including nlohmanns json parser [via CMAKEs fetch content](https://github.com/nlohmann/json#cmake)?

FairRoot should not provide third-party dependencies as a public dependency while not using it itself. Because it is a header-only library, the best course of action is to add such a FetchContent logic or just copy the header file as a private dependency to the project that uses it. If your project uses it as a public dependency we could consider adding it to [FairSoft](https://github.com/FairRootGroup/FairSoft).

> Or is there already an established way to parse json which I'm not familiar with?

I have not used it, but if you already depend on ROOT, https://root.cern.ch/doc/master/classTBufferJSON.html might be interesting to you.
