### ISSUE TITLE
setFirstInput vs setSecondInput in a class FairRuntimeDb

### ISSUE THREAD

**Issue by kurbatov-lang** [FairRootGroup/FairRoot#1185]
What is the difference between them? When an each one to use

in a macro? Why two similar(?) methods were defined in principle?

Thank you

**Comment by fuhlig1** [comment]
@kurbatov-lang,

the reason behind the two very similar versions of the functions are different sources of the parameter information. The main idea is that one only needs one of them getting all parameters from a database as single source of information. But even in such a setup it may become necessary for testing to overwrite an existing parameter or to add a new one. This is where the second source (normally a local file) comes into play. 
If you want to overwrite an already existing parameter you add the local file as first input and the database as second. Whatever parameter container is found in the local file has precedence and will overwrite the parameter container from the database. If you only want to add a new parameter container the order of the inputs isn't important. 

Since I don't know your exact example I can only guess. Assuming that you did transport simulation using FairRoot you create during this step ROOT file which contains several parameter containers which are necessary for FairRoot, e.g. the ROOT file contains the GeoManager which is needed in later stets like digitisation (detector response simulation) and reconstruction. For this later steps normally additional parameter containers are needed (e.g. parameters which describes detector response for a specific detector) which are read from a different input (ASCII or ROOT file) and written normally to the same ROOT parameter file (if specified in the macro).

I hope that helps to understand the idea behind the two different inputs.

**Comment by kurbatov-lang** [comment]
Dear Colleague!

Thank you for the answer,due to my bad english, i should

spend some time to fully understand it.

Thank you again, Vladimir

**Comment by karabowi** [comment]
Reopen if needed.
