### ISSUE TITLE
ROOT dictionary error: only virtual member can be marked 'override'

### ISSUE THREAD

**Issue by YanzhaoW** [FairRootGroup/FairRoot#1320]
**Describe the bug**
I get a "compile" error when running FairRoot example Tutorial1 executable in `build/examples/simulation/Tutorial1/src/tut1`. 

The exact error message is:
```
G__Base dictionary payload:7536:44: error: only virtual member functions can be marked 'override'
      void SetSource(FairSource* tempSource) override;
```
So this must come from ROOT dictionary.

**To Reproduce**
1. compile FairRoot
2. `source build/config.sh`
3. `cd build/examples/simulation/Tutorial1/src/ && ./tut1`

**System information:**
 - OS: macOS 13.1
 - Compiler: Clang 14.0.0
 - Environment: FairSoft@22.11, FairRoot v18.8.0

**Additional context**
1. I use ROOT in fairsoft/bin/root
2. Compilation of FairRoot is successful. But I get compile error when running the executable. 

**Relavent files:**
[G__Base.cxx.zip](https://github.com/FairRootGroup/FairRoot/files/10448271/G__Base.cxx.zip)

**Comment by dennisklein** [comment]
Can you please attach the file `build/base/G__Base.cxx` from your build directory, thx!

**Comment by YanzhaoW** [comment]
> 

Yes, I have added the file to the original post. Please check the zip file on the bottom.

**Comment by YanzhaoW** [comment]
For the further information, changing FairRoot version from v18.8.0 back to v18.6.9 fixes this issue and tut1 does not have this error anymore.

**Comment by ChristianTackeGSI** [comment]
This looks like it references this line in our sources:
https://github.com/FairRootGroup/FairRoot/blob/4ceee18f9a16e020ac4939f8c4facf0278854bca/base/steer/FairRunAnaProof.h#L62

FairRunAnaProof derives from FairRunAna, which derives from FairRun.

https://github.com/FairRootGroup/FairRoot/blob/4ceee18f9a16e020ac4939f8c4facf0278854bca/base/steer/FairRun.h#L199

So I don't understand, what's going on. (Haven't yet tried to reproduce it. … Also I wonder, why our CI didn't catch it yet.)

**Comment by dennisklein** [comment]
Have not figured it out yet neither, but this is my understanding so far:

> ```
> G__Base dictionary payload:7536:44: error: only virtual member functions can be marked 'override'
>      void SetSource(FairSource* tempSource) override;
> ```

This error message looks like it is generated by root cling (because it is thrown at runtime). Upon inspection of the generated `G__Base.cxx` one can find all the header files included there as a string literal (I assume this code is then interpreted at runtime, hence the error message referencing the generated source file). Unfortunately, the embedded header files look ok to me - my guess was that due to some build system problem/bug the file has not been regenerated correctly.

**Comment by ChristianTackeGSI** [comment]
I start to ponder about a bug in ROOT?

Maybe the order of interpreting the included headers is going wrong somehow?
(In the long run, I would prefer that the dictionaries do not include the headers verbatim, but the headers being loaded from the include directory. Last time I tried that, it failed for something else.)

Still I wonder, why our CI doesn't catch that at all?

**Comment by dennisklein** [comment]
65cf2d41b450c3223b4adfe3d8482f9df1f72d88 did move the` SetSource` member function up the inheritance tree to `FairRun` and also moved the definition to the cxx file. Don't see though what is wrong about that.

**Comment by ChristianTackeGSI** [comment]
Does ROOT require the direct parent to have a declaration to `override` (as in "My direct parent does not mention this thing, I am not allowed to override it")?

**Comment by dennisklein** [comment]
> Does ROOT require the direct parent to have a declaration to `override` (as in "My direct parent does not mention this thing, I am not allowed to override it")?

No, tested a couple of things in the root shell. The code works as is.

**Comment by YanzhaoW** [comment]
> > Does ROOT require the direct parent to have a declaration to `override` (as in "My direct parent does not mention this thing, I am not allowed to override it")?
> 
> No, tested a couple of things in the root shell. The code works as is.

Could it be due to the latest version of macOS?

**Comment by dennisklein** [comment]
I managed to reproduce the error on my environment. What is the content of the environment variable `$ROOT_INCLUDE_PATH` when this error happens?

In my case I get the error, if I compile FairRoot 18.8 and run `tut1` as you describe from my 18.8 build directory, but have `$ROOT_INLUDE_PATH` set and pointing to a FairRoot 18.6 include directory. Not sure yet, how this can be produced, but it seems, `$ROOT_INCLUDE_PATH` has precedence over the embedded header files. In general, I recommend to not source multiple (especially from different versions) `FairRootConfig.sh`/`config.sh`s within the same shell session. They will not know about each other and potentially produce a mixed state (although I don't see yet how, but to say the least we are not supporting this use case (serial sourcing of multiple configs)).

**Comment by ChristianTackeGSI** [comment]
Wow!

That also explains, why our CI doesn't see this. Many thanks for tracking this down!

**Comment by klenze** [comment]
> In the long run, I would prefer that the dictionaries do not include the headers verbatim, but the headers being loaded from the include directory.

As far as I understand it this would have the additional benefit that we could use ``#pragma once`` instead of include guards (and thus relying on people putting the same macro name in two subsequent lines).

(Personally, I would rather add support for people to compile their steering macros in a painless way (using g++ or vanilla clang++) and restricting the dictionary stuff to data classes which have to be serializable (e.g. FooData) than dealing with the way ROOT accomplishes runtime reflection of everything. If there is an easy way to tell which definitions of G__Base.cxx actually get loaded by cling and which get skipped because the include guards have been set by a library loaded before, I don't know about it. With gcc, there is always the option to run with -E and figure out which definitions the compiler will actually see.)

Otherwise, some hack involving macros, asserts during library initialization, static_asserts and so on could perhaps been used to prevent mixing of FairRoot headers and libs from different versions. I am not sure if it is worth it, though.

**Comment by YanzhaoW** [comment]
@dennisklein Thanks very much. Yes, I don't have issue anymore after I delete the include directory, reinstall the FairRoot and restart shell.

**Comment by YanzhaoW** [comment]
>  restricting the dictionary stuff to data classes which have to be serializable (e.g. FooData) than dealing with the way ROOT accomplishes runtime reflection of everything.

I totally agree with this because more than one time I have experienced weird behaviours from my code caused by the `ClassDef` in the end of the header file.

What I really can't endure with root dictionary is why the hell we could have compilation error during the run time?

**Comment by klenze** [comment]
> What I really can't endure with root dictionary is why the hell we could have compilation error during the run time?

Well, it think these they should probably be called "interpreter errors". A cling session has to know about the interfaces of a library it loads, so it is not totally unreasonable that it should parse the headers. 
(Of course, my view on interpreting C++ are roughly similar to my views on using GPT2 as a chess engine or IP over avian carriers: the amazing thing is that one can (kinda) make them work at all. Them not being a reasonable substitute for established tech should come at no surprise.)
