### ISSUE TITLE
Processed Event output

### ISSUE THREAD

**Issue by ajedele** [FairRootGroup/FairRoot#1438]
I am using R3BRoot to calibrate data. After I execute the job and the input have loaded, the following appears:

'Processed: $current_event of $total_events ($% of 100), current RunId $runId'

The events are constantly updated. This is a problem when I write the output to a file. The file becomes humongous! I was told this is a feature of FairRoot.

**Describe the solution you'd like**
Could you build in a means to control how often the events processed are outputted?
I would like for the processed events to be printed every 10000 events or 1%. 

**Describe alternatives you've considered**
Having a means to turn off the events processed.

**Comment by klenze** [comment]
@ajedele That is a feature, because it is our excuse for writing log files to lustre. :-)

More seriously, I would argue that status updates should appear at a fixed (real time) rate on the order of 1Hz. This will inform the interactive user that their process is still alive while only creating some 100 bytes per second worth of logs. (If someone needs to figure out if their task crashes in the third or the fifth event, let them write their own printfs.)

@inkdot7 (and I, iirc?) implemented this in [ucesb](https://git.chalmers.se/expsubphys/ucesb/-/blob/master/eventloop/mainfcn.cc#L958) using a sigalarm handler. While this solution is very performant (no extra system call per event), it also depends on specifics of signal handling. (ucesb is in the comfortable position that it does not link to any ROOT libraries directly and at least does not need to worry about what signal handling ROOT might require. Unfortunately, that path does not sound very feasible for FairRoot.)

Some other solutions are:
* extrapolating the event rate to figure out which even no will likely be processed in a second (this will obviously not be very reliable for live data)
* calling ``time(2)`` in the eventloop
* having a separate thread which sets a global bool should_log and then sleeps for a second

**Comment by inkdot7** [comment]
It could be mentioned that the signal approach was not without side-effects, it later turned out. (See comment in ucesb code just below the lines linked by @klenze above).

However, the printout "Processed: "... refered to by @ajedele above seems to come from R3BRoot:
https://github.com/R3BRootGroup/R3BRoot/blob/dev/r3bbase/R3BFileSource.cxx#L485
so the issue should probably be raised there instead.

**Comment by ChristianTackeGSI** [comment]
> […] so the issue should probably be raised there instead.

If I understand that correctly, this does not directly affect FairRoot?

One could read this as a feature request "Please add helpers, so that we can output logs every second". TBH I don't know, if this is the "core business" of FairRoot, or whether this should be handled / helped by some other part?

**Comment by ajedele** [comment]
I was ill informed. I apologize
