### ISSUE TITLE
missing header file in fairmq/logger

### ISSUE THREAD

**Issue by TobiasStockmanns** [FairRootGroup/FairRoot#202]
The installation of the dev branch fails on machines with older boost versions (< 1.56) because of a missing header file. Here is the cmake output:

CMake Error at fairmq/logger/cmake_install.cmake:39 (file):
  file INSTALL cannot find
  "/Users/Stockmanns/PandaSoftware/FairRoot/fairmq/logger/logger_oldboost_version.h".
Call Stack (most recent call first):
  fairmq/cmake_install.cmake:269 (include)
  cmake_install.cmake:78 (include)

**Comment by NicolasWinckler** [comment]
Dear Tobias,

I have added the missing header file, which should fix the issue.

Best regards,

Nicolas



On 24 Sep 2015, at 10:37, Tobias Stockmanns <notifications@github.com<mailto:notifications@github.com>> wrote:


The installation of the dev branch fails on machines with older boost versions (< 1.56) because of a missing header file. Here is the cmake output:

CMake Error at fairmq/logger/cmake_install.cmake:39 (file):
file INSTALL cannot find
"/Users/Stockmanns/PandaSoftware/FairRoot/fairmq/logger/logger_oldboost_version.h".
Call Stack (most recent call first):
fairmq/cmake_install.cmake:269 (include)
cmake_install.cmake:78 (include)
