### ISSUE TITLE
fairmq: design question about FairMQDevice

### ISSUE THREAD

**Issue by sbinet** [FairRootGroup/FairRoot#441]
(I couldn't find the answer to this question anywhere in the fairmq tree...)

why does the `FairMQDevice` class have a field:

```c++
class FairMQDevice : public FairMQStateMachine, public FairMQConfigurable {
public:
std::unordered_map<std::string, std::vector<FairMQChannel>> fChannels; ///< Device channels
};
```

more explicitly:

- why is it public?
- why is it a map of strings to a vector channels? (and not just a map of strings to channels?)

thx.

**Comment by rbx** [comment]
Hi,
it was made public for integration with FairProgOptions. It will be better to rework the interface and make it private. It shouldn't affect any public APIs.

As for the map of vectors - it is to allow easier iteration/selection for channels with the same role. For example if a device sends same type of data to many receivers, while manually selecting destination channel: `("stf").at(i)`. It is easier to make `i` a function of some selection algorithm if it is an index rather than string, or to iterate over all "stf" channels without string conversions. To be more specific it is used in the flp2epn prototype to have destination epnReceiver a function of some meta data.

**Comment by sbinet** [comment]
thanks for explaining the motivations behind `fChannels`.

(the ATLAS framework I used to work suffered from a case of overgeneralization, so I am always worried to encounter such a disease in the s/w stacks I work with nowadays...
But I must admit I don't know whether the `flp2epn` is the exception or the general case, so I can't really comment any further.)

thanks again.
