### ISSUE TITLE
Compiling on Arch Linux fails (c++1y, string_view)

### ISSUE THREAD

**Issue by bl0x** [FairRootGroup/FairRoot#518]
Fairroot correctly figures out that the compiler is capable of c++1y features, but then uses 'fairsoft_config' which adds std=c++11 to the cxx flags. With that configuration the ::std::experimental::basic_string_view cannot properly compile.

A solution is to go back to fair_config and change the value of _cxxflags to ' -std=c++1y'.

**Comment by dennisklein** [comment]
Since this experimental feature is already accepted for C++17, I can try to make argument, that we move our build flags to `--std=c++14` which supports `::std::experimental::basic_string_view`.

@MohammadAlTurany  @fuhlig1 Do you know any reason against moving to C++14? What needs to be done to do that?

**Comment by dennisklein** [comment]
@bl0x After talking with @MohammadAlTurany I learned that currently there are no efforts made to change the `--std=c++11` flag. These kind of flags apparently need to be kept in sync with the build flags of FairRoot's major dependencies (e.g. Root). Until anyone has verified that the `--std=c++14` flag will work for the whole dependency tree, FairRoot/FairSoft will not support `::std::experimental::basic_string_view`. Maybe you can convince your project (R3BRoot I assume?) to override the flag inherited from 'fairsoft_config' for now.

**Comment by dennisklein** [comment]
Closing. Please reopen, if this is not resolved.
