### ISSUE TITLE
Introspection of Device options and channels

### ISSUE THREAD

**Issue by ktf** [FairRootGroup/FairRoot#570]
It would be great if it was actually possible to invoke a device and have it dump:

* The custom program options
* The defined channels

The former of course I can get by massaging the output of `--help`, however it would be nice to avoid the massaging. The latter I am not sure if it is possible at all. Am I missing something (as usual;-))?

**Comment by rbx** [comment]
The channel information is available once some configuration is read (e.g.  `--config-json-string`, `--mq-config` or `--channel-config`). Right now `--help` is evaluated before device starts reading nay of the channel sources.
I can make an extra option, something like `--print-channels`, that reads and prints channels from the source of one of the above options, and then exits the device. Would that be enough for what you have in mind, or do you need to see both via same command?

**Comment by ktf** [comment]
No, I think having a separate `--print-channels` is good enough for now.

**Comment by ktf** [comment]
Mmm... actually no, that will not work... What I am after is generating a default configuration automatically from the device code, if I need to provide the configuration before I can get the list of channels, there is little point into that. Any idea on how to achieve that?

**Comment by ktf** [comment]
or if you prefer the user story:

> As a user I would like to be able to have the device generate for me a configuration fragment which I 
> can then modify and include in the top-level configuration.

**Comment by dennisklein** [comment]
> What I am after is generating a default configuration automatically from the device code. If I need to provide the configuration before I can get the list of channels, there is little point into that. Any idea on how to achieve that?

I could see something like this being possible by creating sort of a runtime _registry_ of channels the user task will access, similar to current FairTasks, but instead of requesting root tree branch names, the task would declare accessing channels by name. Currently, FairMQ does not **require** a _Task_, we have some examples though and the state machine provides some user task oriented states.

> As a user I would like to be able to have the device generate for me a configuration fragment which I
can then modify and include in the top-level configuration.

The authoritative entity, which ultimately dictates channels, is the topology. I would look in the direction of generating configuration, devices and tasks starting from the topology.

**Comment by dennisklein** [comment]
Following up on the channel registry as discussed in the meeting in #572

**Comment by ktf** [comment]
Ok, can we have also the same thing for a more machine readable version of the program option configuration? Something like `--print-options` which returns:

```bash
<option>:<computed-value>:<type>
```

**Comment by rbx** [comment]
Implemented in #593 and documented with #626.
