### ISSUE TITLE
FairMQ include level?

### ISSUE THREAD

**Issue by ktf** [FairRootGroup/FairRoot#590]
Whenever we include FairMQ, do you expect it to be accessed via (e.g.):

```C++
#include <fairmq/FairMQParts.h>
```

or simply:

```C++
#include <FairMQParts.h>
```

I am asking because I just noticed in ALICE O2 we have both. What is the preferred way?

**Comment by dennisklein** [comment]
Since this line in the very recent [commit](https://github.com/FairRootGroup/FairRoot/commit/c596dbdefcfd961f03ed6fc9f293173ee61ba572#diff-11cf7e45d2316da816219c0ab77c9539R190) you can use both as far as FairMQ is concerned. (Probably you could use the first both already before because of some FairRoot related include path configuration which is the same base directory as FairMQ headers are installed to).

Internally, we use `#include <FairMQParts.h>` for all headers that are not in the namespace `fair::mq`. We are in the process of moving everything into this namespace, then the include will be `#include <fairmq/Parts.h>`.

But for now for old headers both includes are supported.

**Comment by ktf** [comment]
Ok, so do I understand correctly that:

```C++
#include <fairmq/Parts.h>
```

is the new and recommended way of doing things?

**Comment by dennisklein** [comment]
Yes. (But note, that Parts.h does not exist yet, but your first example in your first post would be the correct one)

**Comment by ktf** [comment]
Perfect!
