### ISSUE TITLE
Problem running tests or template example

### ISSUE THREAD

**Issue by spflueger** [FairRootGroup/FairRoot#686]
Running the tests using `make test`  does not work. Tests 9 to 52 fail with error message
> Required regular expression not found.Regex

Also running the template as written in the Readme does not work for me. The rename.sh script does not seem to create the required directory structure.
I'm using Fairroot v17.03. Can anyone verify this?

**Comment by MohammadAlTurany** [comment]
Hi @spflueger,
Which system you use and which FairSoft?

**Comment by spflueger** [comment]
Ubuntu 16.04, gcc 6.x, fairsoft may16p1 (but root6.08)

**Comment by MohammadAlTurany** [comment]
Hi,
How did you change the root version? did you use the make_clean.sh script to clean all the dependancies on the old root before updating or you make a new build with the new ROOT?

FairRoot 17.03 with fairsoft may16p1 on ubuntu 16.04 out of the box works without any problem! (see our [CDASH](https://cdash.gsi.de/viewTest.php?onlypassed&buildid=165804) 

Could you make an experimental build with the Dart.sh so that we can see the error messages?

**Comment by spflueger** [comment]
Hi Mohammad,

we installed it on the HIMSTER in the HI in Mainz. The standard fairsoft installation had a few problems. I cannot exactly remember why the version 6.08 was chosen. But I modified the fairroot installation script a bit to install that root version. I could send you the diff for that if you like.

I saw that the CDash works fine (but the previous version failed as well, I'm not sure what was the reason for that). Basically I have troubles running any kind of geant3 with pandaroot (see https://forum.gsi.de/index.php?t=tree&th=5861&start=0&). And now I'm trying to get simple things running and work myself up from there...

Stefan

**Comment by MohammadAlTurany** [comment]
Hi Stefan,

I update ROOT in the may16p1 to ROOT 6.08 and run the tests again, all works without any problem 
(see [CDash](https://cdash.gsi.de/viewTest.php?onlypassed&buildid=165866)). The only difference to your case is the compiler, here I used the default compiler gcc 5.4 and you have gcc 6.x. I will try to update the compiler on the VM that I use to see if this is the reason for your problem.

Any way it would very helpful if you run the Dart.sh in your source directory of FairRoot with experimental build type so that I can see the errors, you need to create a test.cfg file which contains following lines:

```
export LINUX_FLAVOUR=<your linux flavour>                        
export FAIRSOFT_VERSION=<version of FairSoft>                    
export SIMPATH=<path to your FairSoft version>                  
export GIT_BRANCH=< master or dev>                              
export BUILDDIR=<dir where the build files go>                  
export SOURCEDIR=<location of the FairRoot sources>     
```
and then in your FairRoot source directory

`./Dart.sh  Experimental test.cfg
`
Mohammad

**Comment by spflueger** [comment]
Hi Mohammad,

ok good to know. I will run the Dart.sh and post the error log later. Thx for your help

Stefan

**Comment by spflueger** [comment]
Hi Mohammad,

I ran the Dart.sh now and it should have uploaded something. Actually now I see bit more output myself. I think some shared libraries at HIMSTER are broke again...

**Comment by spflueger** [comment]
Yep that worked. So the latest uploaded logfiles are the correct ones

**Comment by MohammadAlTurany** [comment]
Where did you upload them? could you please post the link here?

**Comment by spflueger** [comment]
I could not use https on this machine so I changed to http...

   Using HTTP submit method
   Drop site:http://cdash.gsi.de/submit.php?project=FairRoot
   Uploaded: /home/pflueger/exp_build_fairroot/Testing/20171129-1012/Build.xml
   Uploaded: /home/pflueger/exp_build_fairroot/Testing/20171129-1012/Configure.xml
   Uploaded: /home/pflueger/exp_build_fairroot/Testing/20171129-1012/Test.xml
   Submission successful

**Comment by MohammadAlTurany** [comment]
It seems that something went wrong with the submission, I only get a mail from CDash saying:
An XML submission from 134.93.149.8 to the project FairRoot cannot be parsed. 

However, I could reproduce your problem on ubuntu 16.04 by updating the gcc, g++ and fortran to 6.3. after the update Geant3 crashes randomly with the same message as you posted in the Panda forum. Let see if this is something that we can solve!!
best,
Mohammad

**Comment by spflueger** [comment]
Hi Mohammad,
here is a log file from the tests.

[test.log](https://github.com/FairRootGroup/FairRoot/files/1513902/test.log)

I get two kinds of errors from GEANT3:

> floating point exception 

and also that fatal I posted on the forum

> !!!!!  ZFATAL called from MZTABC

I hope that helps out a bit
Stefan

**Comment by spflueger** [comment]
Ok, @fuhlig1 found out that its related to when building the geant3 shared library with optimizations. Building the geant3 library without any optimizations removes this issue. I'm closing the issue

**Comment by rklasen** [comment]
I suggest reopening this issue, since I've run into it a few days ago on HimsterII. Maybe we can modify the CMakeLists for GEANT so it always compiles without optimizations?

**Comment by spflueger** [comment]
Could you change the building of geant3 to without optimizations, independent of the choice by the user. Because we ran into the same problem, when we installed a new fairsoft package.

**Comment by fuhlig1** [comment]
Hi,

we discussed this again in our meeting and decide to have priority to the user choice since you are obviously the only one with the problem. The situation would be different if a large fraction of the users would have the same problem.
