### ISSUE TITLE
Some suggestions from MPD software team

### ISSUE THREAD

**Issue by kgertsenberger** [FairRootGroup/FairRoot#709]
Good day. Martin asked me to write some suggestions to use the last FairRoot with soft of the NICA experiments separately (now it's inside our soft).
1. in 'parbase/FairParAsciiFileIo.cxx' file:
```
while((string = static_cast<TObjString*>(myIter.Next()))) {
     // check if the file exist
     // if file exist return value is false
    if ( gSystem->AccessPathName(string->GetString())) {
      LOG(FATAL) << "Parameter file " << string->GetString() << " does not exist." << FairLogger::endl;
    }
     //    cout <<  string->GetString() <<endl;
     catCommand += string->GetString();
```
add ExpandPath function because sometimes we use special vars (e.g. $VMCWORKDIR) in our path, so we corrected it the following way:
```
while((string = static_cast<TObjString*>(myIter.Next()))) {
     // check if the file exist
     // if file exist return value is false
      TString strParPath = string->GetString();
      gSystem->ExpandPathName(strParPath);
      if (gSystem->AccessPathName(strParPath))
        LOG(FATAL) << "Parameter file " << strParPath << " does not exist." << FairLogger::endl;
     //    cout <<  string->GetString() <<endl;
     catCommand += string->GetString();
```

2. in 'base/source/FairSource.h' file there are only two source types:
`enum Source_Type {kONLINE, kFILE};`
If we want own data source, how can we add new source type? Now I use source for online raw data from our DAQ system.

3. I have implemented a new Event Display for the NICA experiments from the old FairRoot event display. The most old classes were rewritten. Now it includes three methods of coloring, XML descriptions (i have seen that you added some functions for XML too), some additional functions and buttons...
How can we use new FairRoot version with our evolved Event Display?

Thank you for your support.

**Comment by DanielWielanek** [comment]
Hi,
concerning point 1 & 2 - I think - "we/you/I" should just send proper commits to github (and wait for accepting them) this should not be a problem because those changes are "backward compatible".
Concerning Event Display -
- As far as I know functions of Fair ED  - it should work with old macros - but of course not all Mpd-features are supported (like online display, button for screenshots), I can also provide some example xml-script with transparency/color/settings
- In my opinion we should also change policy and stop "overwriting" FairEventDisplay - because each change in FairROOT mean that we have something to fix/modify. We rather should add as much as possible functionality to FairED + and build Bmn/MpdEventDisplay like classes (only with stuff that cannot be common).
This should be also discussed by FairROOT team - we are focused on Event Display and waiting (sometimes few weeks) for accepting pull request is a problem. In my opinion because Dubna works heavily on EventDisplay and rest of FairRootGroup mostly on MQ-stuff we should have separate branch dedicated only to EventDisplay with possibility of accepting changes by somebody from Dubna, and with each release merge them. 
But of course I'm not boss here, those are only my ideas.

**Comment by MohammadAlTurany** [comment]
Hallo Daniel and  Konstantin, 

I agree with Daniel about the first two points, just make a pull request and we will do it very fast! it will not take weeks I promise! 

Concerning the event display in FairRoot: 

It was done as an example and never meant as a tool to be used by everybody, in Panda for example they have their own implementation of the event display where they add many features for it, that are of course panda specific and uses the panda data format. 
Bottom line is:  The event display in FairRoot is a simply a tool to visualise simulation data with minimum effort. We could add some generic stuff to it (like what Daniel did with the XML) but we cannot add experiment specific stuff to it. This should be part of your code.

It is true that much effort is going to the MQ part but we did not forget the rest and we are moving slowly all FairRoot to the MQ world even the simulation so it would be much easier for you if FairRoot was used as an external package and not fully integrated in your code.
best,

Mohammad

**Comment by kgertsenberger** [comment]
Hello.
1. Thank You, I will make a pull request on Monday.
2. Indeed I think it's a more complex question. Unfortunately, i don't remember why I created new source. May be, some errors occured when i tried to use Online Source. I think I'll try to use default Online Source for BM@N online data one more time, and if there will be errors, i will create a corresponding issue here.
3. I see two possible decisions with Event Display.
The first on: I can prepare a commit with modified common classes of the Fair Event Display where all changes is not specific to experiments: different methods of coloring, XML, some new buttons, some optimizations.
The second. If you don't want these changes and want to save this set of classes as simple and minimal as possible, so I'll just rename my Event Display classes to Mpd[].
You are head of the FairRoot, please, choose which decision is ok.

Thank you.

**Comment by kgertsenberger** [comment]
Dear Mohammad.
I still have some questions:
1. Are you going to release a new tag of the FairRoot environment?
2. And can you answer for my third question above concerned with the Event Display?

Btw, i want to add merge request in order to exclude incorrect error with different compilers in the CheckCompiler module. Is it ok?

**Comment by MohammadAlTurany** [comment]
Hello,

We are releasing a new Fairsoft very soon but we are moving to AliBuild/Alidist 
about the event display:
I prefer to have the generic functionality available to every body (First option) So if you do it, it will be great.

> Btw, i want to add merge request in order to exclude incorrect error with different compilers in the CheckCompiler module. Is it ok?

Yes, it is ok
