### ISSUE TITLE
Slow / bloated compilation when including `FairMQDevice.h`

### ISSUE THREAD

**Issue by ktf** [FairRootGroup/FairRoot#775]
Recently a profiling of O2 compilation has been done by Laurent. Results are available from Laurent [CERNBox](https://cernbox.cern.ch/index.php/s/1jJmvxrFFTNsjWC).

This shows quite well the fact that Framework, DataFlow and other heavy users of FairMQ are by far the biggest offender in compilation time. Moreover if one looks into the BUILD directory for O2 they will see that when make is used the files which cmake generates to keep track of dependencies  explode for the same components, culprit being the fact that something brings in `boost.fusion` and `boost.mpl` which are well known monstrosities when it comes to compilation time, and bring in a very large fraction of boost public interface at each invocation of GCC.

The reason for this is that because `FairMQDevice` inherits from `FairMQStateMachine` which inherits from `boost::state_machine` which itself uses a lot of `boost::mpl` and `boost::fusion`. Any inclusion of `FairMQDevice.h` will result in an extremely large reparsing of basically the whole set of boost headers.

Would it be possible to refactor code to hide the whole boost world when including `FairMQDevice`? As we write more and more devices (which is good!) this starts to hurt people efficiency quite a lot.

**Comment by dennisklein** [comment]
Thank you for your input. We are aware of the issue and are already discussing solutions internally for a while. The issue just didn't have the highest priority in the past. We have increased the priority, let's continue any discussion in FairRootGroup/FairMQ#35.

**Comment by ktf** [comment]
FairRootGroup/FairMQ#35 is a separate issue. I do agree with dropping boost completely, but that is orthogonal to what I am asking and a far larger chunk of work.

My point is that regardless of how you implement the state machine, I think the FairMQDevice headers should not expose that detail but have a forward reference. I think actually that FairMQDevice fails the "is a FairMQStateMachie" rule and therefore I would refactor code to use composition (and a forward reference in the header) rather than inheritance.

**Comment by dennisklein** [comment]
> I do agree with dropping boost completely, but that is orthogonal to what I am asking and a far larger chunk of work.

An alternative "lightweight" implemention already exists, see `fairmq/StateMachine.h`. It adresses also a small bug the current implementation has. But we never finished this effort, because there were other issues with higher priority and my colleagues could not be convinced so far to use this code.

> ... FairMQDevice headers should not expose that detail ...

We also already have such a refactored version done, and are currently looking at it again to make sure it adresses your points. Still, if we go for such an intermediate step or not, we have already reached consensus to get rid of Boost.MSM completely, that is why I took your issue to push this effort. One reason why this effort has not happened yet is, that we would like to use Boost.SML instead, but it needs a C++14 compiler we cannot require yet...

> the state machine one and the message sender one, and I would like to have those refactored apart.

`FairMQChannel` has the pure message passing responsibility and API - that's the message passing library part of FairMQ. Is that what you mean with proxy class?

When it comes to orchestrate a user task with cli/file configuration, the state machine, an optional event loop, builtin controller, etc, then you go for a device - that's the framework (basically taking over your main function with prepared customization points) part of FairMQ.

**Comment by ktf** [comment]
I can understand that rewriting the state machine is a big undertaking, where writing the code is only one of the factors to take into account. That's why I was saying it should be considered orthogonal. What is the ETA for either the rewrite or the forward declaration to happen?

Regarding `FairMQChannel`, no, that's not what I mean. A `FairMQDevice` has multiple channels to juggle and the current `FairMQDevice::Send` API hides that from the user. Moreover the current `FairMQDevice` provides methods as `Serialize`, `NewMessage` which are not there (correctly) in the `FairMQChannel` but which are in general required for a client to be able to send messages in a convenient way.

**Comment by rbx** [comment]
I tested moving all boost headers into from FairMQStateMachine.h to FairMQStateMachine.cxx.
After moving **all** boost headers from the header to the source file (plus the required refactoring), the compile time went down, but less significantly than I was hoping. For the entire FairMQ repository from 5.6 mins to 4.9 mins. We do have some number devices due to examples and tests, not sure if more or less than O2.
I also took a look at the size of the cmake products, here is an overview:

| component | boost in .cxx | boost in .h |
| --- | --- | --- |
| fairmq-ex-1-1-sampler.dir/depend.make | 392K | 431K |
| fairmq-ex-1-1-sink.dir/depend.make | 376K | 414K |
| Example1N1Lib.dir/depend.make | 1.1M | 1.2M |
| fairmq-ex-1-n-1-processor.dir/depend.make | 413K | 454K |
| fairmq-ex-1-n-1-sampler.dir/depend.make | 403K | 443K |
| fairmq-ex-1-n-1-sink.dir/depend.make | 387K | 425K |
| ExampleCopyPushLib.dir/depend.make | 763K | 840K |
| fairmq-ex-copypush-sampler.dir/depend.make | 419K | 460K |
| fairmq-ex-copypush-sink.dir/depend.make | 403K | 443K |
| ExampleDDSLib.dir/depend.make | 1.1M | 1.2M |
| fairmq-ex-dds-processor.dir/depend.make | 403K | 443K |
| fairmq-ex-dds-sampler.dir/depend.make | 392K | 431K |
| fairmq-ex-dds-sink.dir/depend.make | 376K | 414K |
| ExampleMultipartLib.dir/depend.make | 774K | 852K |
| fairmq-ex-multipart-sampler.dir/depend.make | 424K | 466K |
| fairmq-ex-multipart-sink.dir/depend.make | 408K | 449K |
| ExampleMultipleChannelsLib.dir/depend.make | 1.3M | 1.4M |
| fairmq-ex-multiple-channels-broadcaster.dir/depend.make | 487K | 536K |
| fairmq-ex-multiple-channels-sampler.dir/depend.make | 466K | 513K |
| fairmq-ex-multiple-channels-sink.dir/depend.make | 450K | 495K |
| ExampleMultipleTransportsLib.dir/depend.make | 1.3M | 1.5M |
| fairmq-ex-multiple-transports-sampler1.dir/depend.make | 482K | 530K |
| fairmq-ex-multiple-transports-sampler2.dir/depend.make | 482K | 530K |
| fairmq-ex-multiple-transports-sink.dir/depend.make | 461K | 507K |
| ExampleRegionLib.dir/depend.make | 742K | 817K |
| fairmq-ex-region-sampler.dir/depend.make | 408K | 449K |
| fairmq-ex-region-sink.dir/depend.make | 392K | 431K |
| ExampleReqRepLib.dir/depend.make | 750K | 826K |
| fairmq-ex-req-rep-client.dir/depend.make | 408K | 449K |
| fairmq-ex-req-rep-server.dir/depend.make | 408K | 449K |
| fairmq-bsampler.dir/depend.make | 395K | 434K |
| FairMQ.dir/depend.make  | 13M  | 13M |
| fairmq-merger.dir/depend.make | 363K | 399K |
| fairmq-multiplier.dir/depend.make | 384K | 422K |
| fairmq-proxy.dir/depend.make | 358K | 393K |
| fairmq-sink.dir/depend.make | 352K | 387K |
| fairmq-splitter.dir/depend.make | 374K | 411K |
| runConfigExample.dir/depend.make | 383K | 422K |
| FairMQPlugin_dds.dir/depend.make | 390K | 427K |
| FairMQPlugin_test_dummy2.dir/depend.make | 405K | 446K |
| FairMQPlugin_test_dummy.dir/depend.make | 400K | 440K |
| testhelper_runTestDevice.dir/depend.make | 4.9M | 5.4M |
| testsuite_FairMQ.Device.dir/depend.make | 822K | 904K |
| testsuite_FairMQ.Plugins.dir/depend.make | 810K | 891K |
| testsuite_FairMQ.PluginServices.dir/depend.make | 868K | 954K |
| testsuite_FairMQ.PluginsPrelinked.dir/depend.make | 464K | 510K |
| testsuite_FairMQ.Protocols.dir/depend.make | 2.7M | 2.7M |
| testsuite_FairMQ.StateMachine.dir/depend.make | 432K | 432K |
| **total** | **44.869M** | **47.769M** |

Perhaps I am still missing some detail, I will investigate further. The refactored code needs a bit more polishing anyway. But in principle this is not a breaking change and can be done very soon, as opposed to a complete rewrite.

**Comment by dennisklein** [comment]
`FairMQChannel` does provide the `NewMessage` APIs. It was taken care of a while ago to separate the message passing APIs from the device to support a meaningful usage of a standalone `FairMQChannel` instance.

**Comment by ktf** [comment]
Nice! We should probably have a rule that no boost headers can creep in either FairRoot or O2...

**Comment by dennisklein** [comment]
@rbx's improvements are available in the development release [FairMQ 1.2.2](https://github.com/FairRootGroup/FairMQ/releases/tag/v1.2.2).

**Comment by dennisklein** [comment]
@ktf The improvements should be visible with `--defaults o2` now. Can you verify? Do you consider this issue as resolved or are we missing anything still?

**Comment by ktf** [comment]
Thank you for doing this. I trust you and consider this closed. If I spot anything else, I will open a new bug report.
