### ISSUE TITLE
Create a clang-format config file and enforce it with a PR check

### ISSUE THREAD

**Issue by dennisklein** [FairRootGroup/FairRoot#943]

**Comment by rbx** [comment]
If we adopt a format that O2 uses, we should consult @mattkretz, he co-authored those and if i remember correctly doesn't agree with 100% of what is in those rules.

**Comment by dennisklein** [comment]
For reference, the [`git-clang-format` script](https://github.com/llvm-mirror/clang/blob/master/tools/clang-format/git-clang-format) can be used in a PR check to only apply clang-format against the PR diff.

**Comment by fuhlig1** [comment]
I reopen the issue because I found a code snippet which isn't corrected by clang-format and which I actually don't like. So I would like to discuss this here and come to a common decision.

```
if (fCanvas)
   fCanvas->Write();
```

What I don't like about the statement is that it is error prone when you add a second line which should be in the if statement. From the indentation it looks like but actually only the first line is in the if. We had already some cases where this problem appears. If you have newer compiler and the right compiler flags you may get a warning but this is not guaranteed  .

I would propose either to force such statements on one line

```
if (fCanvas) fCanvas->Write();
```
  
which make the intention more clear or even to force curly brackets also for one line if statements

```
if (fCanvas) {
  fCanvas->Write();
}
```
 Your opinions are very welcome.

**Comment by mattkretz** [comment]
I think a clang-format check would actually catch an error like when you edit the above to:
```c++
if (fCanvas)
   debug(fCanvas);
   fCanvas->Write();
```
Now your formatting is wrong and gets flagged. If you blindly apply clang-format after editing and don't notice the indent (and intent) change, that's really dangerous.

Requesting one-liners doesn't help for long lines (e.g. conditions). Clang-format would still have to break the line somewhere.

Enforcing braces for one-line `if` blocks is not something clang-format can do, AFAIK. That would need a different style checker.

**Comment by rbx** [comment]
I would prefer to always have braces.
Indeed I couldn't find a clang-format check that does this.
But there is a clang-tidy check [that does](https://clang.llvm.org/extra/clang-tidy/checks/readability-braces-around-statements.html).
I propose to leave this open until we have a clang-tidy checker as well and then add that rule to our rule set.

**Comment by dennisklein** [comment]
`clang-tidy` is nowadays also (integrated with CMake)[https://cmake.org/cmake/help/latest/variable/CMAKE_LANG_CLANG_TIDY.html], so it is easy to add a clang-tidy build to the CI. I can add it in a few days, when I finished my script to manage the new containerized alfa-ci environments (I already attempted to add such a check a while ago, but postponed it because none of our current CI environments easily provided a clang-tidy system package, and I didn't want to compile it myself.)

**Comment by dennisklein** [comment]
If someone has a meaningful and smallish configuration for clang-tidy, pls send it to me. The default config will blow up our servers ;)

**Comment by rbx** [comment]
We could start by only whitelisting a few rules that we want, and add gradually from that.

**Comment by dennisklein** [comment]
> We could start by only whitelisting a few rules that we want, and add gradually from that.

Sounds good, could you prepare such a whitelist of rules you want to have included? Thx

**Comment by rbx** [comment]
`readability-braces-around-statements`.
Didn't look into more rules as of now.
I can run with the default one and see what of it makes sense. But there will be several rules that make a lot of sense but will require breaking 90% of FairRoot compatibility.

**Comment by rbx** [comment]
I did a brief run with clang-tidy with FairMQ/FairRoot to try and find useful checks that can be whitelisted. Here is what I found so far.

Whitelist:

| check | why? |
| ----- | ---- |
| [misc-unused-alias-decls](https://clang.llvm.org/extra/clang-tidy/checks/misc-unused-alias-decls.html) | remove useless code |
| [misc-unused-parameters](https://clang.llvm.org/extra/clang-tidy/checks/misc-unused-parameters.html) | avoid mistakes |
| [modernize-deprecated-headers](https://clang.llvm.org/extra/clang-tidy/checks/modernize-deprecated-headers.html) | replace deprecated headers with c++ alternatives |
| [modernize-raw-string-literal](https://clang.llvm.org/extra/clang-tidy/checks/modernize-raw-string-literal.html) | readability |
| [modernize-redundant-void-arg](https://clang.llvm.org/extra/clang-tidy/checks/modernize-redundant-void-arg.html) | readability |
| [modernize-use-bool-literals](https://clang.llvm.org/extra/clang-tidy/checks/modernize-use-bool-literals.html) | readability |
| [modernize-use-default-member-init](https://clang.llvm.org/extra/clang-tidy/checks/modernize-use-default-member-init.html) | readability |
| [modernize-use-emplace](https://clang.llvm.org/extra/clang-tidy/checks/modernize-use-emplace.html) | performance potential |
| [modernize-use-equals-default](https://clang.llvm.org/extra/clang-tidy/checks/modernize-use-equals-default.html) | readability |
| [modernize-use-equals-delete](https://clang.llvm.org/extra/clang-tidy/checks/modernize-use-equals-delete.html) | readability |
| [modernize-use-noexcept](https://clang.llvm.org/extra/clang-tidy/checks/modernize-use-noexcept.html) | avoid deprecated style |
| [modernize-use-nullptr](https://clang.llvm.org/extra/clang-tidy/checks/modernize-use-nullptr.html) | readability |
| [modernize-use-override](https://clang.llvm.org/extra/clang-tidy/checks/modernize-use-override.html) | avoid mistakes |
| [modernize-use-using](https://clang.llvm.org/extra/clang-tidy/checks/modernize-use-using.html) | readability |
| [performance-faster-string-find](https://clang.llvm.org/extra/clang-tidy/checks/performance-faster-string-find.html) | performance |
| [performance-for-range-copy](https://clang.llvm.org/extra/clang-tidy/checks/performance-for-range-copy.html) | performance |
| [performance-unnecessary-copy-initialization](https://clang.llvm.org/extra/clang-tidy/checks/performance-unnecessary-copy-initialization.html) | performance |
| [readability-avoid-const-params-in-decls](https://clang.llvm.org/extra/clang-tidy/checks/readability-avoid-const-params-in-decls.html) | readability |
| [readability-braces-around-statements](https://clang.llvm.org/extra/clang-tidy/checks/readability-braces-around-statements.html) | readability |
| [readability-container-size-empty](https://clang.llvm.org/extra/clang-tidy/checks/readability-container-size-empty.html) | readability |
| [readability-delete-null-pointer](https://clang.llvm.org/extra/clang-tidy/checks/readability-delete-null-pointer.html) | readability |
| [readability-redundant-member-init](https://clang.llvm.org/extra/clang-tidy/checks/readability-redundant-member-init.html) | readability |
| [readability-redundant-string-init](https://clang.llvm.org/extra/clang-tidy/checks/readability-redundant-string-init.html) | readability |
| [readability-static-accessed-through-instance](https://clang.llvm.org/extra/clang-tidy/checks/readability-static-accessed-through-instance.html) | readability |
| [readability-string-compare](https://clang.llvm.org/extra/clang-tidy/checks/readability-string-compare.html) | readability |

Disable:

| check | why? |
| ----- | ---- |
| [llvm-header-guard](https://clang.llvm.org/extra/clang-tidy/checks/llvm-header-guard.html) | style dependent. We should fix our own style instead |
| [modernize-use-trailing-return-type](https://clang.llvm.org/extra/clang-tidy/checks/modernize-use-trailing-return-type.html) | readability improvement in very few cases, in vast majority it only increases verbosity. imo. purely stylistic and subjective. |

Following checks i think can be useful to warn about, but do not have to be enforced. Some are also configurable:

| check | why? |
| ----- | ---- |
| [bugprone-unused-return-value](https://clang.llvm.org/extra/clang-tidy/checks/bugprone-unused-return-value.html) |  |
| [cppcoreguidelines-avoid-goto](https://clang.llvm.org/extra/clang-tidy/checks/cppcoreguidelines-avoid-goto.html) |  |
| [llvm-include-order](https://clang.llvm.org/extra/clang-tidy/checks/llvm-include-order.html) |  |
| [llvm-namespace-comment](https://clang.llvm.org/extra/clang-tidy/checks/llvm-namespace-comment.html) |  |
| [misc-non-private-member-variables-in-classes](https://clang.llvm.org/extra/clang-tidy/checks/misc-non-private-member-variables-in-classes.html) |  |
| [misc-unused-using-decls](https://clang.llvm.org/extra/clang-tidy/checks/misc-unused-using-decls.html) | should be safe to apply in cxx, but in headers might break users |
| [modernize-loop-convert](https://clang.llvm.org/extra/clang-tidy/checks/modernize-loop-convert.html) | could be safe always, check options |
| [modernize-use-auto](https://clang.llvm.org/extra/clang-tidy/checks/modernize-use-auto.html) | I would apply this everywhere where the type is clear from nearby context, but not if it hides the type |
| [modernize-use-transparent-functors](https://clang.llvm.org/extra/clang-tidy/checks/modernize-use-transparent-functors.html) | cool, but c++14? |
| [performance-unnecessary-value-param](https://clang.llvm.org/extra/clang-tidy/checks/performance-unnecessary-value-param.html) | very good, but needs special care not to break users of existing code |
| [modernize-pass-by-value](https://clang.llvm.org/extra/clang-tidy/checks/modernize-pass-by-value.html) | very good, but needs special care not to break users of existing code |
| [readability-isolate-declaration](https://clang.llvm.org/extra/clang-tidy/checks/readability-isolate-declaration.html) |  |
| [readability-magic-numbers](https://clang.llvm.org/extra/clang-tidy/checks/readability-magic-numbers.html) |  |
| [readability-named-parameter](https://clang.llvm.org/extra/clang-tidy/checks/readability-named-parameter.html) |  |
| [readability-simplify-boolean-expr](https://clang.llvm.org/extra/clang-tidy/checks/readability-simplify-boolean-expr.html) |  |

These checks triggered with FairRoot and/or FairMQ, but i didn't yet look in detail on what is best there:

```
bugprone-branch-clone
bugprone-copy-constructor-init
bugprone-exception-escape
bugprone-forward-declaration-namespace
bugprone-forwarding-reference-overload
bugprone-integer-division
bugprone-macro-parentheses
bugprone-misplaced-widening-cast
bugprone-move-forwarding-reference
bugprone-parent-virtual-call
bugprone-sizeof-expression
bugprone-suspicious-enum-usage
bugprone-suspicious-string-compare
bugprone-unhandled-self-assignment
bugprone-virtual-near-miss
cert-dcl50-cpp
cert-env33-c
cert-err34-c
cert-err58-cpp
cppcoreguidelines-macro-usage
cppcoreguidelines-narrowing-conversions
cppcoreguidelines-no-malloc
cppcoreguidelines-owning-memory
cppcoreguidelines-pro-bounds-array-to-pointer-decay
cppcoreguidelines-pro-bounds-constant-array-index
cppcoreguidelines-pro-type-cstyle-cast
cppcoreguidelines-pro-type-member-init
cppcoreguidelines-pro-type-static-cast-downcast
cppcoreguidelines-pro-type-vararg
cppcoreguidelines-slicing
cppcoreguidelines-special-member-functions
hicpp-exception-baseclass
hicpp-multiway-paths-covered
hicpp-no-assembler
hicpp-signed-bitwise
misc-definitions-in-headers
modernize-avoid-c-arrays
performance-inefficient-string-concatenation
performance-move-const-arg
performance-noexcept-move-constructor
readability-const-return-type
readability-convert-member-functions-to-static
readability-else-after-return
readability-implicit-bool-conversion
readability-inconsistent-declaration-parameter-name
readability-non-const-parameter
readability-redundant-smartptr-get
readability-redundant-string-cstr
```

I **did not** run `abseil-*`, `android-*`, `darwin-*`, `fuchsia-*`, `google-*`, `mpi-*`, `objc-*`, `openmp-*`, `zircon-*`. 

`clang-analyzer-*` checks behaved a bit weird when i tried to run them one by one, perhaps I missed something there.

These checks were not available for use on my system, perhaps too old clang version:
```
bugprone-bad-signal-to-kill-thread
bugprone-dynamic-static-initializers
bugprone-infinite-loop
bugprone-misplaced-pointer-arithmetic-in-alloc
bugprone-not-null-terminated-result
bugprone-reserved-identifier
bugprone-signed-char-misuse
bugprone-spuriously-wake-up-functions
bugprone-suspicious-include
cert-mem57-cpp
cert-oop57-cpp
cert-oop58-cpp
cppcoreguidelines-init-variables
linuxkernel-must-use-errs
llvm-prefer-register-over-unsigned
llvmlibc-callee-namespace
llvmlibc-implementation-in-namespace
llvmlibc-restrict-system-libc-headers
misc-no-recursion
performance-no-automatic-move
performance-trivially-destructible
portability-restrict-system-includes
readability-make-member-function-const
readability-qualified-auto
readability-redundant-access-specifiers
```

All the other checks did not find anything in FairMQ/FairRoot (I ran using `run-clang-format` with `compile_commands.json`), but still might be useful - need further investigation.

Here is [my full list](https://docs.google.com/spreadsheets/d/1moLsv2-wu1or12G_e8n1Hys2aGbQYF2IqsmtzovaQtM/edit?usp=sharing).
Compare with [official](https://clang.llvm.org/extra/clang-tidy/checks/list.html).

This is just preliminary so that I'm not alone looking at this. Although a lot of it looks reasonable, I didn't yet try to apply all of them, perhaps there are surprises. Leave your thoughts, once we agree on the whitelist I can apply in FairMQ and FairRoot.
