### ISSUE TITLE
ex_MQ_* tests sometimes fails to write root file

### ISSUE THREAD

**Issue by dennisklein** [FairRootGroup/FairRoot#977]
`ex_MQ_pixel_simulation` test:
https://cdash.gsi.de/testDetails.php?test=6660419&build=235863

In the last 50 executions it failed 3 times with the error above.

**Comment by dennisklein** [comment]
Extends to the other `ex_MQ*` tests:
https://cdash.gsi.de/viewTest.php?onlyfailed&buildid=235887
https://cdash.gsi.de/testDetails.php?test=6661469&build=235891

**Comment by karabowi** [comment]
The underlying, and more interesting problem, is, imho, different.
My MQ tests are often crashing, and I had problems to reproduce the problem on my machine for a long time. Finally I was able to understand the problem. The tests fail when I start "make test" from two different build directories on one machine at the same time. The test order is usually the same and the tests are taking approximately the same time. While for standard root tests they can run simultaneously, it is not the case for MQ tests. They _do_ share the same port numbers.

Currently in order to avoid unwanted interferences between devices, I am checking for already running MQ test, and kill them appropriately, i.e. if device ids match.

I am not seeing any simple way to fix this. I could randomize the port numbers - good, but would still fail from time to time. I could wait some seconds before killing the running processes - ok, but eventually could hit the timeout limit.

Any suggestions on how to fix this?

**Comment by dennisklein** [comment]
Yes, we should use DDS to launch the the examples/tutorials. This is a longstanding Todo. Unfortunately, we have migrated a couple of examples in FairMQ to launch via DDS, but this is not working reliably.

In O2 they have switched to the named pipe address format (`ipc://<some string>`) (supported for zmq and shmem transports) for their single machine testing, because it does not need tcp port mgmt at all.

**Comment by dennisklein** [comment]
If you give want to give DDS a try, see this example shell script https://github.com/FairRootGroup/FairMQ/blob/master/examples/dds/fairmq-start-ex-dds.sh.in.

The types of errors we get, you can browse here https://cdash.gsi.de/testSummary.php?project=16&name=Example.DDS.localhost&date=2020-05-25. We have pending issues with DDS team on various of those hangs and crashes, but without any solution so far.

**Comment by dennisklein** [comment]
Checked `ex_MQ_pixel_simulation` runs from the last two days:

[2022-11-16](https://cdash.gsi.de/testSummary.php?project=3&name=ex_MQ_pixel_simulation&date=2022-11-16): 98% passed, 4 failed out of 195.
[2022-11-17](https://cdash.gsi.de/testSummary.php?project=3&name=ex_MQ_pixel_simulation&date=2022-11-17): 98% passed, 2 failed out of 124.

The failed ones can be sorted into the following categories:
1. `There are 3000 events in the output file. Shell script finished successfully.` but it still is reported as failure. ([355882](https://cdash.gsi.de/testDetails.php?test=12772816&build=355882), [356275](https://cdash.gsi.de/testDetails.php?test=12789979&build=356275))
2. `There are [2994|2996|2845] events in the output file. Shell script failed.` ([355669](https://cdash.gsi.de/testDetails.php?test=12763439&build=355669), [355730](https://cdash.gsi.de/testDetails.php?test=12765571&build=355730). [355839](https://cdash.gsi.de/testDetails.php?test=12770891&build=355839), []())
3. `examples/MQ/pixelDetector/run/test-pixelSim.sh: line 45: 31831 Segmentation fault      dds-info --executing-count --wait $NOFNEEDEDAGENTS` ([356354](https://cdash.gsi.de/testDetails.php?test=12793584&build=356354)) - this was reported long time ago https://github.com/FairRootGroup/DDS/issues/261, possibly fixed in more recent versions after 3.6, let's wait for next release.

**Comment by karabowi** [comment]
Closing for now. Reopen if needed.
Many of the MQ test failures are probably connected to running tests in parallel,
which is no good for hardcoded IP addresses.
