### ISSUE TITLE
Please disable Geant3 tests by default

### ISSUE THREAD

**Issue by ChristianTackeGSI** [FairRootGroup/FairRoot#995]
**Is your feature request related to a problem? Please describe.**
We want to enable unit tests during spack install (at least in the `+examples` variant). And the geant3 based tests seem to fail randomly. That's not good for a simple `spack install`.

**Describe the solution you'd like**
Please add an option like `-DENABLE_EXTRA_TESTS` that is `OFF` by default and only do the `add_test()` if that define is `ON`.
At least, that was the conclusion a few weeks ago.

**Describe alternatives you've considered**
* We could only run tests if `spack install` is given the "run tests" option and ignore them otherwise. But we still would like to run the tests in our FairSoft CI to make sure, that – say geant4 – is still good. So that would not help.
* We could rerun the test like 4 times until one works out.

**Additional context**
* First list of tests to be marked optional: https://cdash.gsi.de/testDetails.php?test=7009626&build=243455
  * `42 - ex_tutorial3_reco_timebased_TGeant3 (Failed)`
  * `43 - ex_tutorial3_digi_reco_proof_TGeant3 (Failed)`
  * `50 - ex_sim_rutherford_TGeant3 (Failed)`
  * `51 - ex_sim_run_rad_TGeant3 (Failed)`
* I can try to create the patch / PR. Please advice on
  * preferred name of the option.
  * other things I should be aware of.

**Comment by dennisklein** [comment]
As a consequence of *having to live* with Geant3 being unstable on 64bit, I support disabling Geant3 testing by default of 64bit (see #1004). There is really no value in seeing them fail every other run of the test suite just to ignore them.

* As a CMake switch I suggest `ENABLE_GEANT3_TESTING` to keep the scope of the switch to the point.
* In order to not lose test coverage, we should keep test invocations with Geant4 enabled (or add them if missing) (unless the test is specific about Geant3)
* CI: For branch pushes use `-DENABLE_GEANT3_TESTING=ON`, but not for PRs.
